imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@BackendBundle/Resources/config/services.yml" }
    - { resource: "@BackendBundle/Resources/config/repository.yml" }
    - { resource: "@BackendBundle/Resources/config/manager.yml" }
    - { resource: "@BackendBundle/Resources/config/controller.yml" }
    - { resource: "@AdminBundle/Resources/config/services.yml" }
    - { resource: "@AdminBundle/Resources/config/controller.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    agent_files_data_dir: '%kernel.root_dir%/../app/db/fixtures/agents'
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

jms_di_extra:
    locations:
        all_bundles: false
        bundles: [BackendBundle]
        directories: ["%kernel.root_dir%/../src"]

# Doctrine Extensions
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true
            uploadable: true

knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: AdminBundle::knp_menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig

vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    mappings:
        agent_head_shot:
            uri_prefix:         /uploads/images/agent
            upload_destination: "%kernel.root_dir%/../web/uploads/images/agent"
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid
        agent_document:
            #uri_prefix:         /app/documents/agent
            #upload_destination: "%kernel.root_dir%/../app/documents/agent"
            uri_prefix:         /storage/fathomdocs
            upload_destination: /storage/fathomdocs
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        agent_head_shot:
            quality: 90
            filters:
                thumbnail: { size: [100, 100], mode: outbound }
