security:
    hide_user_not_found:  false

    encoders:
        BackendBundle\Entity\User:
            algorithm: md5
            encode-as-base64: false
            iterations: 0

    role_hierarchy:
        ROLE_AGENT:             [ROLE_USER]
        ROLE_ADMIN:             [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN:       [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        users_db:
            entity: { class: BackendBundle\Entity\User, property: email }

        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern:   ^/
            anonymous: true
            switch_user: true
            form_login:
                provider:            users_db
                login_path:          backend_login
                check_path:          backend_login
                default_target_path: admin_dashboard
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:                backend_logout
                target:              backend_login
            remember_me:
                secret:      '%secret%'
                lifetime: 31536000 # 365 days in seconds
                path: /

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: [ROLE_USER] }
